### PR TITLE
Added Ubuntu dependency installation instructions

### PR DESCRIPTION
**Pull request by thelifeofjay**
why not make an easier machine easier?

### CODE REVIEW

**Comment by TingPing** [comment]
- Use `apt` not `apt-get`
- Seems like you listed random dependencies?
  - libtk2.0-dev ?
  - libperl-dev ?
  - unecessary libotr5, glib-2.0, gcrypt (non-dev packages)
  - missing glib-2.0-dev, libgcrypt20-dev

**Comment by darknetj** [comment]
@TingPing installation on vanilla Ubuntu required these exact dependencies to compile with ```./autogen.sh```

**Comment by TingPing** [comment]
Maybe `build-essential` could be added to the list but those other two seem completely unrelated.

**Comment by darknetj** [comment]
@TingPing unrelated or not - this is what is required for your ./autogen to work

**Comment by TingPing** [comment]
I need more information than "That is just what was required" do you have errors that lead you to this packages?

**Pull request closed without merging**
